export const noteConstants = {
	SET_NOTES_CATAGORIES: 'SET_NOTES_CATAGORIES',
	SET_ALL_NOTES: 'SET_ALL_NOTES',
	SET_LAST_DELETE_NOTE: 'SET_LAST_DELETE_NOTE',
	SET_CURRENT_SELECTED_NOTE: 'SET_CURRENT_SELECTED_NOTE',
	SET_CURRENT_SELECTED_NOTE_CATEGORY_INDEX: 'SET_CURRENT_SELECTED_NOTE_CATEGORY_INDEX',
	DEL_A_NOTE: ' DEL_A_NOTE',
	UPDATE_NOTE_STATUS: 'UPDATE_NOTE_STATUS',
	RENAMED_CATEGORY:"Rename Category",
	DELETE_CATEGORY:"Delete Category",
	DELETE_ALL_COMPLETED_NOTES:"Delete all completed notes",
	SET_SORT_ON_PARAMETER:"SET_SORT_ON_PARAMETER",
};
