export const userConstants = {
    SET_USER_LOGIN_STATUS:'SET_USER_LOGIN_STATUS',
    SET_USER_DATA:"SET_USER_DATA",
    SET_GUEST_USER_STATUS:"SET_GUEST_USER_STATUS",
    SET_AUTH_ERROR_MSG: "SET_AUTH_ERROR_MSG",
    SET_TO_INITIAL_STATE:"SET_TO_INITIAL_STATE",
}